### ISSUE TITLE
event and signal are not thread-safe: ABBA problem can happen

### ISSUE THREAD

**Issue by sergey-shambir** [i42output/neolib#7]
Here in class `event` library calls foreign callbacks under mutex lock:

```
template<class... Ts>
bool sync_trigger(Ts&&... aArguments) const
{
	if (!has_instance_data()) // no instance date means no subscribers so no point triggering.
		return true;
	destroyable_mutex_lock_guard<event_mutex> guard{ iMutex };
	// ...
```

Imagine that one thread connects to "event1" own function "slot1" which fires "event2". First, it locks "event1" mutex, then attempts to lock "event2" mutex.

Another thread connects to "event2" own function "slot2" which fires "event1". First, it locks "event2" mutex, then attempts to lock "event1" mutex.

In some cases, threads will enter into deadlock: thread1 always waits "event2" mutex, while thread2 always waits "event1" mutex.

**Comment by i42output** [comment]
Problem resolved: exception thrown if deadlock detected.

**Comment by sergey-shambir** [comment]
This fix isn't ideal: no deadlock doesn't happen, but signals/slot library can throw suspicious exceptions when threads access signals concurrently.

Imagine following case:
![default](https://user-images.githubusercontent.com/1856842/44581336-f95f1280-a7a5-11e8-8515-99752361c926.png)

In this case, two threads may concurrently try to connect new slot (or even call signal) while another signal has locked mutex. With deadlock detection, this code will throw. Such behavior can cause heisenbugs in software.

Another solution is to avoid calling signal slot under deadlock. This solution can lead to changes in data structures, but looks like it's the only way to avoid

**Comment by i42output** [comment]
Problem resolved; deadlocks have been removed.
